### ISSUE TITLE
Timeline alignment

### ISSUE THREAD

**Issue by mado-bohsali** [chulwoo-park/timelines#29]
How can I align the Timeline left or right?

**Comment by chulwoo-park** [comment]
You can align each TimelineNode:

* Use the `nodePosition` in the `TimelineThemeData`.
* Use the `position` in the `TimelineNode` when building each TimelineNode. 

These property will be used in the `TimelineTile`.

If you want align timeline to the right, set the node position to 1.0.

Check out the themes section of the [demo web](https://chulwoo.dev/timelines)!

**Comment by Sakthivelgovindan** [comment]
yeah, it's working✌️, @chulwoo-park
