### ISSUE TITLE
Migrate to sound null safety 

### ISSUE THREAD

**Issue by adarsh-technocrat** [chulwoo-park/timelines#31]
### **Description**

- Migrate to sound null safety
- Bump up package version

**Comment by dungnv2602** [comment]
Just Ping to kindly remind @chulwoo-park to migrate this beautiful package to null-safety, because otherwise, it would a huge waste for the community.

**Comment by KabinManandhar** [comment]
Another reminder for @chulwoo-park to migrate the package to null safety, its been a while :)

**Comment by jigarfumakiya** [comment]
Hey, @chulwoo-park Any update on null safety?

**Comment by robertonic** [comment]
I'd like to echo the request for a null sage version

**Comment by chulwoo-park** [comment]
@jigarfumakiya #33 will resolve this issue.
