### ISSUE TITLE
Question : How to align the nodes to the left ?

### ISSUE THREAD

**Issue by adbonnin** [chulwoo-park/timelines#34]
Hi,

I would like to align the nodes to the left in order to have a fixed size for the content and the remaining space for the opposite content. There is a property `nodeAlign` in `TimelineTile` that used to compute the effective node position :

```dart
  double _getEffectiveNodePosition(BuildContext context) {
    if (nodeAlign == TimelineNodeAlign.start) return 0.0;
    if (nodeAlign == TimelineNodeAlign.end) return 1.0;
    var nodePosition = this.nodePosition;
    nodePosition ??= (node is TimelineTileNode)
        ? (node as TimelineTileNode).getEffectivePosition(context)
        : TimelineTheme.of(context).nodePosition;
    return nodePosition;
  }
```

This property can't be used in `TimelineTileBuilder` so please what is the simplest way to define the `nodeAlign` ?

**Comment by chulwoo-park** [comment]
Try using `nodePosition` in TimelineTheme?

Check how it works [here (Theme)](https://chulwoo.dev/timelines/#/)

**Comment by pierre-gancel** [comment]
Great package !

```dart
Timeline.tileBuilder(theme: TimelineThemeData(connectorTheme: ConnectorThemeData(space: 51)))

**Comment by adbonnin** [comment]
> Try using `nodePosition` in TimelineTheme?
> 
> Check how it works [here (Theme)](https://chulwoo.dev/timelines/#/)

nodePosition works but it's the a percentage between 0 and 1.
If the screen is too small then the oppositeContent width will shrink it's content.
What I'm looking for is a fixed width for oppositeContent and the remaining width for the content.


> ```dart
> Timeline.tileBuilder(theme: TimelineThemeData(connectorTheme: ConnectorThemeData(space: 51)))
> ```

Connector's space is the space between the content and the oppositeContent, it's not the width of the oppositeContent.

**Comment by chulwoo-park** [comment]
@adbonnin 

I got it. 

There is no option yet to provide the feature you are talking about.😢

Since it uses Flexible internally, I think it is necessary to explicitly limit the size of the opossite content.

**Comment by adbonnin** [comment]
ok thank you 😄

**Comment by om1ji** [comment]
This worked for me:

```flutter
return Timeline.tileBuilder(
      theme: TimelineThemeData(nodePosition: 0), // Все ноды сместить налево
)
```

The `nodePosition` parameter required `double` type, just put zero in there
