### ISSUE TITLE
Hundreds of data

### ISSUE THREAD

**Issue by paulocoutinhox** [chulwoo-park/timelines#36]
Hi,

Can i used it with hundred of data like a list that is recycled?

I want make something like this:

![image](https://user-images.githubusercontent.com/395096/114414243-04e4ef00-9b85-11eb-8b14-e645f1c01316.png)

Is it possible?

Thanks.

**Comment by chulwoo-park** [comment]
Yes.

Use builder constructor to recycle items. But timelines doesn't seems to support your use case.
