### ISSUE TITLE
null-safety release is not available

### ISSUE THREAD

**Issue by jseminck** [chulwoo-park/timelines#38]
Hi, according to the changelog there should be a version available `0.1.0-null` which includes null-safety changes, but when I try to set this version in my `pubspec.yaml` then I get an error that this version is not available

pubspec.yaml:
```
timelines: 0.1.0-null
```

error:
```
Because project depends on timelines 0.1.0-null which doesn't match any versions, version solving failed.
```

version from pub.dev:
![image](https://user-images.githubusercontent.com/9586897/116505425-847ff700-a8c3-11eb-8bb9-a8ed7c2c30e4.png)

**Comment by westy92** [comment]
@jseminck try just `timelines: 0.1.0`

**Comment by chulwoo-park** [comment]
This is my mistake
Use `0.1.0`
