### ISSUE TITLE
How to change length of connector?

### ISSUE THREAD

**Issue by SardorbekR** [chulwoo-park/timelines#44]
I want it to take all available space evenly, or how can I change length of the connector?

<img width="400" alt="Screen Shot 2021-07-15 at 12 23 05" src="https://user-images.githubusercontent.com/30071369/125746483-009026a0-1722-4899-8848-776ad1190853.png">

**This is my code:**
<img width="627" alt="Screen Shot 2021-07-15 at 12 25 43" src="https://user-images.githubusercontent.com/30071369/125746813-91ada4e0-1dad-44c9-815e-2e3e655fd8db.png">

**Comment by chulwoo-park** [comment]
The connector is part of the tile.
Tiles have the same size as the child widget(contents or indicator) by default, so you can resize each child widgets to be the same size.
